#cloud-config
#
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html
#
# save this file to /var/lib/vz/snippets/user-data.yaml
# then attach to VM
# qm set 3000 --cicustom "user=local:snippets/user-data.yaml"
#
# To create a hash password use mkpasswd -m sha256crypt
hostname: ubuntu
manage_etc_hosts: true
users:
  - name: user
    primary_group: user
    groups: users,sudo
    ssh_authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9+BtHHqA3zwKhPgrpq7QKEvYWg3R7+UhnNCM/cle/hH+vdYxBVlZX7>
    lock_passwd: false
    sudo: ALL=(ALL:ALL) ALL
    shell: /bin/bash
    passwd: $5$DBixnFvFilsffP0R$WB.ruOyaVtbBPiKrxhSGEXNLgz1ovD.ITjOfA6ftLJ0
chpasswd:
  expire: False
package_upgrade: true # Upgrade packages
packages: ['qemu-guest-agent'] # Install packages
ssh_pwauth: True  # Enabled password Authentication to ssh
runcmd:
  - [touch, /etc/cloud/cloud-init.disabled]
  - [shutdown]

